version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testTask_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  liquibase:
   image: liquibase/liquibase:4.4.0
   container_name: liquibase-container
   command: --url=jdbc:mysql://db:3306/testTask_db --username=root --password=1234 --changeLogFile=classpath:db/changelog/db.changelog-master.xml update
   volumes:
     - ./src/main/resources/db/changelog:/liquibase/classpath/db/changelog
   depends_on:
     - db


volumes:
  db_data:
