version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testTask_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306/testTask_db?allowPublicKeyRetrieval=true -user=root -password=1234 -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db

volumes:
  db_data:
